#!/bin/bash
# ── awww_generate_themes.sh ──────────────────────────────────────────
# Reads pywal colors from ~/.cache/wal/colors.sh and generates
# dynamic theme files for zellij, yazi, and superfile.
#
# Called from awww_randomize_multi.sh after each wallpaper change.
# Can also be run standalone to regenerate themes from current colors.

WAL_COLORS="$HOME/.cache/wal/colors.sh"

if [ ! -f "$WAL_COLORS" ]; then
	echo "awww_generate_themes: $WAL_COLORS not found, skipping" >&2
	exit 1
fi

# shellcheck source=/dev/null
source "$WAL_COLORS"

# ── Hex→RGB helper ──────────────────────────────────────────────────
# Zellij themes use space-separated RGB decimal values (e.g. "255 128 0")
hex_to_rgb() {
	local hex="${1#\#}"
	printf "%d %d %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# ── Color assignments (semantic mapping from pywal) ──────────────────
# background = color0   (darkest)
# foreground = color7   (lightest)
# color1 = red/accent1  (used for errors, highlights)
# color2 = green/accent2
# color3 = yellow/accent3
# color4 = blue/accent4
# color5 = magenta/accent5
# color6 = cyan/accent6
# color8 = bright black (dim text)

BG_RGB=$(hex_to_rgb "$background")
FG_RGB=$(hex_to_rgb "$foreground")
C0_RGB=$(hex_to_rgb "$color0")
C1_RGB=$(hex_to_rgb "$color1")
C2_RGB=$(hex_to_rgb "$color2")
C3_RGB=$(hex_to_rgb "$color3")
C4_RGB=$(hex_to_rgb "$color4")
C5_RGB=$(hex_to_rgb "$color5")
C6_RGB=$(hex_to_rgb "$color6")
C7_RGB=$(hex_to_rgb "$color7")
C8_RGB=$(hex_to_rgb "$color8")

# ═══════════════════════════════════════════════════════════════════════
# 1. ZELLIJ THEME
# ═══════════════════════════════════════════════════════════════════════
ZELLIJ_THEME="$HOME/.config/zellij/themes/pywal.kdl"

cat >"$ZELLIJ_THEME" <<EOF
// Auto-generated by awww_generate_themes.sh from pywal colors
// Source wallpaper: ${wallpaper:-unknown}
themes {
    pywal {
        // ── Text (bare UI text like Ctrl/Alt indicators) ────────
        text_unselected {
            base $FG_RGB
            background $BG_RGB
            emphasis_0 $C4_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }
        text_selected {
            base $BG_RGB
            background $C4_RGB
            emphasis_0 $FG_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }

        // ── Ribbons (tabs, mode indicators in status bar) ───────
        ribbon_unselected {
            base $FG_RGB
            background $C8_RGB
            emphasis_0 $C4_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }
        ribbon_selected {
            base $BG_RGB
            background $C4_RGB
            emphasis_0 $FG_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }

        // ── Tables (session manager, plugin manager) ────────────
        table_title {
            base $C5_RGB
            background $BG_RGB
            emphasis_0 $C4_RGB
            emphasis_1 $FG_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }
        table_cell_unselected {
            base $FG_RGB
            background $BG_RGB
            emphasis_0 $C4_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }
        table_cell_selected {
            base $BG_RGB
            background $C4_RGB
            emphasis_0 $FG_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }

        // ── Lists (nested lists in UI) ──────────────────────────
        list_unselected {
            base $FG_RGB
            background $BG_RGB
            emphasis_0 $C4_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }
        list_selected {
            base $BG_RGB
            background $C4_RGB
            emphasis_0 $FG_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }

        // ── Frames (pane borders) ───────────────────────────────
        frame_unselected {
            base $C8_RGB
            background $BG_RGB
            emphasis_0 $C4_RGB
            emphasis_1 $C5_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }
        frame_selected {
            base $C4_RGB
            background $BG_RGB
            emphasis_0 $C5_RGB
            emphasis_1 $FG_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }
        frame_highlight {
            base $C5_RGB
            background $BG_RGB
            emphasis_0 $C4_RGB
            emphasis_1 $FG_RGB
            emphasis_2 $C6_RGB
            emphasis_3 $C3_RGB
        }

        // ── Exit codes ──────────────────────────────────────────
        exit_code_success {
            base $C2_RGB
            background $BG_RGB
            emphasis_0 $C2_RGB
            emphasis_1 $C2_RGB
            emphasis_2 $C2_RGB
            emphasis_3 $C2_RGB
        }
        exit_code_error {
            base $C1_RGB
            background $BG_RGB
            emphasis_0 $C1_RGB
            emphasis_1 $C1_RGB
            emphasis_2 $C1_RGB
            emphasis_3 $C1_RGB
        }

        // ── Multiplayer ─────────────────────────────────────────
        multiplayer_user_colors {
            player_1 $C1_RGB
            player_2 $C2_RGB
            player_3 $C3_RGB
            player_4 $C4_RGB
            player_5 $C5_RGB
            player_6 $C6_RGB
            player_7 $C8_RGB
            player_8 $FG_RGB
            player_9 $C0_RGB
            player_10 $C7_RGB
        }
    }
}
EOF

echo "awww_generate_themes: wrote $ZELLIJ_THEME"

# ═══════════════════════════════════════════════════════════════════════
# 2. YAZI THEME
# ═══════════════════════════════════════════════════════════════════════
YAZI_THEME="$HOME/.config/yazi/theme.toml"

cat >"$YAZI_THEME" <<EOF
# Auto-generated by awww_generate_themes.sh from pywal colors
# Source wallpaper: ${wallpaper:-unknown}
# DO NOT EDIT — will be overwritten on next wallpaper change.

# ── Flavor (disabled — using dynamic pywal colors) ───────────────────
# [flavor]
# dark = "tokyo-night"

# ── App ──────────────────────────────────────────────────────────────
[app]
overall = { bg = "${background}" }

# ── Manager ──────────────────────────────────────────────────────────
[mgr]
cwd              = { fg = "${color4}", italic = true }
find_keyword     = { fg = "${color3}", bold = true }
find_position    = { fg = "${color5}", italic = true }
symlink_target   = { fg = "${color6}", italic = true }
marker_copied    = { fg = "${color2}", bg = "${color2}" }
marker_cut       = { fg = "${color1}", bg = "${color1}" }
marker_marked    = { fg = "${color5}", bg = "${color5}" }
marker_selected  = { fg = "${color4}", bg = "${color4}" }
count_copied     = { fg = "${background}", bg = "${color2}" }
count_cut        = { fg = "${background}", bg = "${color1}" }
count_selected   = { fg = "${background}", bg = "${color4}" }
border_symbol    = "│"
border_style     = { fg = "${color8}" }

# ── Indicator ────────────────────────────────────────────────────────
[indicator]
parent  = { fg = "${color6}" }
current = { fg = "${color4}" }
preview = { fg = "${color8}" }

# ── Tabs ─────────────────────────────────────────────────────────────
[tabs]
active   = { fg = "${background}", bg = "${color4}", bold = true }
inactive = { fg = "${foreground}", bg = "${color8}" }

# ── Mode ─────────────────────────────────────────────────────────────
[mode]
normal_main = { fg = "${background}", bg = "${color4}", bold = true }
normal_alt  = { fg = "${color4}", bg = "${background}" }
select_main = { fg = "${background}", bg = "${color2}", bold = true }
select_alt  = { fg = "${color2}", bg = "${background}" }
unset_main  = { fg = "${background}", bg = "${color5}", bold = true }
unset_alt   = { fg = "${color5}", bg = "${background}" }

# ── Status bar ───────────────────────────────────────────────────────
[status]
overall        = { fg = "${foreground}", bg = "${background}" }
perm_type      = { fg = "${color4}" }
perm_read      = { fg = "${color2}" }
perm_write     = { fg = "${color1}" }
perm_exec      = { fg = "${color3}" }
perm_sep       = { fg = "${color8}" }
progress_label = { fg = "${foreground}", bold = true }
progress_normal = { fg = "${color4}", bg = "${background}" }
progress_error  = { fg = "${color1}", bg = "${background}" }

# ── Which key popup ──────────────────────────────────────────────────
[which]
cols            = 3
mask            = { bg = "${background}" }
cand            = { fg = "${color4}" }
rest            = { fg = "${color8}" }
desc            = { fg = "${foreground}" }
separator       = " → "
separator_style = { fg = "${color8}" }

# ── Confirm dialog ───────────────────────────────────────────────────
[confirm]
border  = { fg = "${color4}" }
title   = { fg = "${color4}", bold = true }
body    = { fg = "${foreground}" }
list    = { fg = "${foreground}" }
btn_yes = { fg = "${background}", bg = "${color4}" }
btn_no  = { fg = "${foreground}", bg = "${color8}" }

# ── Spot (table view) ───────────────────────────────────────────────
[spot]
border   = { fg = "${color4}" }
title    = { fg = "${color4}", bold = true }
tbl_col  = { fg = "${color5}" }
tbl_cell = { fg = "${foreground}" }

# ── Notifications ────────────────────────────────────────────────────
[notify]
title_info  = { fg = "${color4}" }
title_warn  = { fg = "${color3}" }
title_error = { fg = "${color1}" }

# ── Pick (selection popup) ───────────────────────────────────────────
[pick]
border   = { fg = "${color4}" }
active   = { fg = "${background}", bg = "${color4}" }
inactive = { fg = "${foreground}" }

# ── Input ────────────────────────────────────────────────────────────
[input]
border   = { fg = "${color4}" }
title    = { fg = "${color4}", bold = true }
value    = { fg = "${foreground}" }
selected = { fg = "${background}", bg = "${color4}" }

# ── Completion ───────────────────────────────────────────────────────
[cmp]
border       = { fg = "${color4}" }
active       = { fg = "${background}", bg = "${color4}" }
inactive     = { fg = "${foreground}" }
icon_file    = ""
icon_folder  = ""
icon_command = ""

# ── Tasks ────────────────────────────────────────────────────────────
[tasks]
border  = { fg = "${color4}" }
title   = { fg = "${color4}", bold = true }
hovered = { fg = "${background}", bg = "${color4}" }

# ── Help ─────────────────────────────────────────────────────────────
[help]
on      = { fg = "${color4}" }
run     = { fg = "${color5}" }
desc    = { fg = "${foreground}" }
hovered = { fg = "${background}", bg = "${color4}" }
footer  = { fg = "${color8}" }

# ── File types ───────────────────────────────────────────────────────
[filetype]
rules = [
    # Images
    { mime = "image/*",               fg = "${color3}" },
    # Audio / Video
    { mime = "{audio,video}/*",       fg = "${color5}" },
    # Archives
    { mime = "application/{*zip,tar,bzip*,7z*,rar,xz}", fg = "${color1}" },
    # Documents
    { mime = "application/pdf",       fg = "${color2}" },
    { mime = "text/*",                fg = "${foreground}" },
    # Empty files
    { mime = "inode/empty",           fg = "${color8}" },
    # Orphan symlinks
    { url = "*", is = "orphan",       fg = "${color1}" },
    # Symlinks
    { url = "*", is = "link",         fg = "${color6}", italic = true },
    # Executables
    { url = "*", is = "exec",         fg = "${color2}" },
    # Directories
    { url = "*/",                     fg = "${color4}", bold = true },
]
EOF

echo "awww_generate_themes: wrote $YAZI_THEME"

# ═══════════════════════════════════════════════════════════════════════
# 3. SUPERFILE THEME
# ═══════════════════════════════════════════════════════════════════════
SUPERFILE_THEME="$HOME/.config/superfile/theme/pywal.toml"

cat >"$SUPERFILE_THEME" <<EOF
##############################################
#                                            #
#             Pywal Dynamic Theme            #
#                                            #
##############################################

# Auto-generated by awww_generate_themes.sh from pywal colors
# Source wallpaper: ${wallpaper:-unknown}
# DO NOT EDIT — will be overwritten on next wallpaper change.

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

code_syntax_highlight = "monokai"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "${foreground}"
full_screen_bg = "${background}"

#-- Gradient
gradient_color = ["${color4}", "${color5}"]

#-- File Panel
file_panel_fg = "${foreground}"
file_panel_bg = "${background}"
file_panel_border = "${color8}"
file_panel_border_active = "${color4}"
file_panel_top_directory_icon = "${color2}"
file_panel_top_path = "${color4}"
file_panel_item_selected_fg = "${color5}"
file_panel_item_selected_bg = "${background}"

#-- Footer
footer_fg = "${foreground}"
footer_bg = "${background}"
footer_border = "${color8}"
footer_border_active = "${color2}"

#-- Sidebar
sidebar_fg = "${foreground}"
sidebar_bg = "${background}"
sidebar_title = "${color6}"
sidebar_border = "${background}"
sidebar_border_active = "${color1}"
sidebar_item_selected_fg = "${color5}"
sidebar_item_selected_bg = "${background}"
sidebar_divider = "${color8}"

#-- Modals
modal_fg = "${foreground}"
modal_bg = "${background}"
modal_border_active = "${color8}"
modal_cancel_fg = "${background}"
modal_cancel_bg = "${color1}"
modal_confirm_fg = "${background}"
modal_confirm_bg = "${color6}"

#-- Help Menu
help_menu_hotkey = "${color6}"
help_menu_title = "${color1}"

#-- Special
cursor = "${foreground}"
correct = "${color2}"
error = "${color1}"
hint = "${color6}"
cancel = "${color1}"
EOF

echo "awww_generate_themes: wrote $SUPERFILE_THEME"
