pragma Singleton
pragma ComponentBehavior: Bound

import qs.modules.common
import QtQuick
import Quickshell
import Quickshell.Io

/**
 * Watches the generated Material You color JSON file and applies colors
 * to Appearance.m3colors. Reloads automatically when wallpaper changes.
 */
Singleton {
    id: root
    property string filePath: Directories.generatedMaterialThemePath

    function reapplyTheme() {
        themeFileView.reload()
    }

    function applyColors(fileContent) {
        // Short-circuit when a static theme is selected. StaticThemeLoader
        // owns the m3colors writes in that mode.
        if ((Config.options?.appearance?.theme?.source ?? "materialYou") !== "materialYou")
            return

        // Preview-tokens overlay (set by AppearanceConfig hover-preview)
        // wins over Material You output — the user is peeking at a static
        // theme. StaticThemeLoader applies the overlay; we step aside
        // until the preview clears (mouse-leave or click-commit).
        if (Appearance.previewTokens && typeof Appearance.previewTokens === "object") {
            for (const _ in Appearance.previewTokens) return // non-empty → defer
        }

        const json = JSON.parse(fileContent)
        for (const key in json) {
            if (json.hasOwnProperty(key)) {
                const camelCaseKey = key.replace(/_([a-z])/g, g => g[1].toUpperCase())
                const m3Key = `m3${camelCaseKey}`
                Appearance.m3colors[m3Key] = json[key]
            }
        }
        Appearance.m3colors.darkmode = (Appearance.m3colors.m3background.hslLightness < 0.5)
    }

    function resetFilePathNextTime() {
        resetFilePathNextWallpaperChange.enabled = true
    }

    Connections {
        id: resetFilePathNextWallpaperChange
        enabled: false
        target: Config.options.background
        function onWallpaperPathChanged() {
            root.filePath = ""
            root.filePath = Directories.generatedMaterialThemePath
            resetFilePathNextWallpaperChange.enabled = false
        }
    }

    Timer {
        id: delayedFileRead
        interval: Config.options?.hacks?.arbitraryRaceConditionDelay ?? 100
        repeat: false
        running: false
        onTriggered: root.applyColors(themeFileView.text())
    }

    FileView {
        id: themeFileView
        path: Qt.resolvedUrl(root.filePath)
        watchChanges: true
        // Generated by matugen on first wallpaper change — absent on a
        // fresh install. Suppress the read-error warning until then.
        printErrors: false
        onFileChanged: { this.reload(); delayedFileRead.start() }
        onLoadedChanged: root.applyColors(themeFileView.text())
        onLoadFailed: root.resetFilePathNextTime()
    }
}
